export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-14">
      <div className="max-w-3xl mx-auto px-4">
        <h1 className="text-3xl font-black text-slate-900 mb-2">Privacy Policy</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: April 2025</p>

        <div className="bg-white rounded-2xl border border-slate-100 p-8 space-y-8 text-sm text-slate-700 leading-relaxed">
          {[
            {
              title: '1. Information We Collect',
              body: 'We collect information you provide directly (name, email, phone number when booking a test drive) and information generated by your use of AutoDrive (cars viewed, search queries, booking history).',
            },
            {
              title: '2. How We Use Your Information',
              body: 'We use collected data to provide and improve our services, send booking confirmations and reminders, personalise car recommendations, and communicate product updates. We never sell your personal data to third parties.',
            },
            {
              title: '3. Data Storage',
              body: 'Your data is stored on Microsoft Azure infrastructure in India (Central India region). All data at rest is encrypted using AES-256. All data in transit is encrypted using TLS 1.2 or higher.',
            },
            {
              title: '4. Cookies',
              body: 'We use session cookies for authentication and analytics cookies (first-party only) to understand how visitors use the site. You may disable cookies in your browser, though some features may not function correctly.',
            },
            {
              title: '5. Your Rights',
              body: 'You have the right to access, correct, or delete your personal data at any time. To exercise these rights, email us at privacy@autodrive.in. We will respond within 30 days.',
            },
            {
              title: '6. Third-Party Services',
              body: 'AutoDrive uses Google OAuth and GitHub OAuth for authentication. These services have their own privacy policies. We receive only your name and email address via OAuth and do not have access to your passwords.',
            },
            {
              title: '7. Changes to This Policy',
              body: 'We may update this policy from time to time. We will notify you of significant changes by email or by posting a notice on our website. Continued use of AutoDrive after changes constitutes acceptance of the updated policy.',
            },
            {
              title: '8. Contact',
              body: 'Questions about this policy? Email privacy@autodrive.in or write to AutoDrive, IIT Delhi, Hauz Khas, New Delhi 110016.',
            },
          ].map(({ title, body }) => (
            <section key={title}>
              <h2 className="font-bold text-slate-900 mb-2">{title}</h2>
              <p>{body}</p>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
