apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autodrive.fullname" . }}-shared
  labels:
    {{- include "autodrive.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CARS_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendUrl | quote }}
  OAUTH_BASE_URL: {{ .Values.secrets.oauthBaseUrl | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
