apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autodrive.fullname" . }}-shared
  labels:
    {{- include "autodrive.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CARS_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  REVIEWS_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  FRONTEND_URL: {{ .Values.secrets.frontendUrl | quote }}
