import { Car, Brand } from './types';

export const cars: Car[] = [
  {
    id: '1',
    make: 'Maruti Suzuki',
    model: 'Swift',
    year: 2022,
    price: 750000,
    mlPrice: 720000,
    mileage: 22000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    location: 'Delhi',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80',
    ],
    color: 'White',
    description: 'Well-maintained Swift with full service history. Single owner, accident-free. Perfect city car with excellent fuel economy.',
    owners: 1,
    rating: 4.5,
    reviews: 24,
    features: ['ABS', 'Airbags', 'Reverse Camera', 'Bluetooth', 'Keyless Entry'],
    engineCC: 1197,
    seating: 5,
  },
  {
    id: '2',
    make: 'Hyundai',
    model: 'Creta',
    year: 2023,
    price: 1450000,
    mlPrice: 1480000,
    mileage: 8000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    location: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1583267746897-2cf415887172?w=600&q=80',
    color: 'Silver',
    description: 'Nearly new Creta SX(O) with panoramic sunroof, ventilated seats. Loaded with features, barely driven.',
    owners: 1,
    rating: 4.8,
    reviews: 12,
    features: ['Sunroof', 'Ventilated Seats', 'ADAS', 'Wireless Charging', 'Connected Car'],
    engineCC: 1493,
    seating: 5,
  },
  {
    id: '3',
    make: 'Tata',
    model: 'Nexon EV',
    year: 2023,
    price: 1680000,
    mlPrice: 1620000,
    mileage: 12000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    location: 'Bangalore',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80',
    color: 'Blue',
    description: 'Tata Nexon EV Max with 437km range. Full charge in 8.5hrs. Home charger included. Zero emission, zero worries.',
    owners: 1,
    rating: 4.7,
    reviews: 31,
    features: ['437km Range', 'Home Charger', 'Connected Car', 'Sunroof', 'ADAS'],
    seating: 5,
  },
  {
    id: '4',
    make: 'Honda',
    model: 'City',
    year: 2021,
    price: 980000,
    mlPrice: 950000,
    mileage: 35000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    location: 'Pune',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80',
    color: 'Red',
    description: 'Honda City VX with leather seats and sunroof. Regular service done at Honda ASS. Excellent condition.',
    owners: 1,
    rating: 4.3,
    reviews: 18,
    features: ['Sunroof', 'Leather Seats', 'Lane Watch', 'Rear AC Vents', 'Cruise Control'],
    engineCC: 1498,
    seating: 5,
  },
  {
    id: '5',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2021,
    price: 3200000,
    mlPrice: 3150000,
    mileage: 42000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    location: 'Delhi',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    color: 'Black',
    description: 'Toyota Fortuner Legender 4x2. Single owner corporate car. Full OEM accessories. Pristine condition.',
    owners: 1,
    rating: 4.9,
    reviews: 9,
    features: ['4x2', 'Leather Seats', 'JBL Audio', 'Wireless Charging', 'ADAS'],
    engineCC: 2755,
    seating: 7,
  },
  {
    id: '6',
    make: 'Kia',
    model: 'Seltos',
    year: 2022,
    price: 1350000,
    mlPrice: 1380000,
    mileage: 18000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    location: 'Chennai',
    image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600&q=80',
    color: 'Grey',
    description: 'Kia Seltos GTX+ with Bose audio, HUD, and ventilated seats. Top variant, fully loaded.',
    owners: 1,
    rating: 4.6,
    reviews: 22,
    features: ['Bose Audio', 'HUD', 'Ventilated Seats', 'Wireless Charging', 'Sunroof'],
    engineCC: 1395,
    seating: 5,
  },
  {
    id: '7',
    make: 'MG',
    model: 'Hector',
    year: 2020,
    price: 1150000,
    mlPrice: 1100000,
    mileage: 55000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    location: 'Hyderabad',
    image: 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=600&q=80',
    color: 'White',
    description: 'MG Hector Sharp with 10.4" touchscreen and connected car tech. Well maintained by first owner.',
    owners: 1,
    rating: 4.2,
    reviews: 16,
    features: ['10.4" Touchscreen', 'Connected Car', 'Sunroof', 'TPMS', 'Wireless Android Auto'],
    engineCC: 1451,
    seating: 5,
  },
  {
    id: '8',
    make: 'Mahindra',
    model: 'XUV700',
    year: 2022,
    price: 2200000,
    mlPrice: 2250000,
    mileage: 25000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    location: 'Kolkata',
    image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80',
    color: 'Red',
    description: 'Mahindra XUV700 AX7L with ADAS, dual 10.25" screens, Sony audio. 7-seater family SUV.',
    owners: 1,
    rating: 4.7,
    reviews: 28,
    features: ['ADAS', 'Dual Screens', 'Sony Audio', 'Panoramic Sunroof', 'AWD'],
    engineCC: 2184,
    seating: 7,
  },
  {
    id: '9',
    make: 'Volkswagen',
    model: 'Polo',
    year: 2019,
    price: 620000,
    mlPrice: 600000,
    mileage: 48000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    location: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
    color: 'Blue',
    description: 'Volkswagen Polo Highline. German build quality, solid performer. Regular service at VW ASS.',
    owners: 2,
    rating: 4.1,
    reviews: 11,
    features: ['ABS', 'Airbags', 'Climatronic AC', 'Alloy Wheels', 'Rear Camera'],
    engineCC: 999,
    seating: 5,
  },
  {
    id: '10',
    make: 'BMW',
    model: '3 Series',
    year: 2021,
    price: 4500000,
    mlPrice: 4350000,
    mileage: 28000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    location: 'Delhi',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80',
    color: 'Black',
    description: 'BMW 330i M Sport. Corporate owned, immaculate condition. Full BMW service history. Loaded with M Sport extras.',
    owners: 1,
    rating: 4.9,
    reviews: 7,
    features: ['M Sport Body Kit', 'Harman Kardon', 'Head-Up Display', 'Parking Assistant', 'Driving Modes'],
    engineCC: 1998,
    seating: 5,
  },
  {
    id: '11',
    make: 'Renault',
    model: 'Kwid',
    year: 2020,
    price: 380000,
    mlPrice: 370000,
    mileage: 32000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    location: 'Jaipur',
    image: 'https://images.unsplash.com/photo-1607664887510-2d5f53de8d79?w=600&q=80',
    color: 'Orange',
    description: 'Renault Kwid RXT with 8" MediaNAV. Great entry-level car with stylish SUV-inspired design.',
    owners: 1,
    rating: 4.0,
    reviews: 20,
    features: ['8" Touchscreen', 'MediaNAV', 'Rear Camera', 'Airbags', 'ABS'],
    engineCC: 999,
    seating: 5,
  },
  {
    id: '12',
    make: 'Skoda',
    model: 'Slavia',
    year: 2023,
    price: 1680000,
    mlPrice: 1650000,
    mileage: 5000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    location: 'Ahmedabad',
    image: 'https://images.unsplash.com/photo-1617469767824-5cbcf2cfd4f7?w=600&q=80',
    color: 'Silver',
    description: 'Skoda Slavia Style 1.5 TSI DSG. Nearly new with Czech engineering precision. Fun to drive.',
    owners: 1,
    rating: 4.8,
    reviews: 6,
    features: ['1.5 TSI DSG', 'Ventilated Seats', 'Sunroof', 'Connected Car', 'Matrix LED'],
    engineCC: 1498,
    seating: 5,
  },
];

export const brands: Brand[] = [
  { name: 'Maruti Suzuki', logo: '🚗', count: 4523 },
  { name: 'Hyundai', logo: '🚙', count: 3210 },
  { name: 'Tata', logo: '🚘', count: 2876 },
  { name: 'Honda', logo: '🏎', count: 2341 },
  { name: 'Toyota', logo: '🚐', count: 1987 },
  { name: 'Kia', logo: '🚗', count: 1654 },
  { name: 'Mahindra', logo: '🚙', count: 1432 },
  { name: 'BMW', logo: '🏎', count: 876 },
];

export const locations = [
  'All Cities', 'Delhi', 'Mumbai', 'Bangalore', 'Chennai',
  'Pune', 'Hyderabad', 'Kolkata', 'Ahmedabad', 'Jaipur',
];

export function formatPrice(price: number): string {
  if (price >= 10000000) return `₹${(price / 10000000).toFixed(2)} Cr`;
  if (price >= 100000) return `₹${(price / 100000).toFixed(2)} L`;
  return `₹${price.toLocaleString('en-IN')}`;
}

export function getCarById(id: string): Car | undefined {
  return cars.find(c => c.id === id);
}

export function filterCars(filters: Partial<{
  make: string; minPrice: number; maxPrice: number;
  fuelType: string; transmission: string; location: string;
  search: string;
}>): Car[] {
  return cars.filter(car => {
    if (filters.make && filters.make !== 'All' && car.make !== filters.make) return false;
    if (filters.minPrice && car.price < filters.minPrice) return false;
    if (filters.maxPrice && car.price > filters.maxPrice) return false;
    if (filters.fuelType && filters.fuelType !== 'All' && car.fuelType !== filters.fuelType) return false;
    if (filters.transmission && filters.transmission !== 'All' && car.transmission !== filters.transmission) return false;
    if (filters.location && filters.location !== 'All Cities' && car.location !== filters.location) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      if (!`${car.make} ${car.model} ${car.year}`.toLowerCase().includes(q)) return false;
    }
    return true;
  });
}
